input.onButtonPressed(Button.B, function () {
    kitronik_klip_motor_with_bluetooth.motorOn(kitronik_klip_motor_with_bluetooth.Motors.Motor1, kitronik_klip_motor_with_bluetooth.MotorDirection.Forward, 75)
    kitronik_klip_motor_with_bluetooth.motorOn(kitronik_klip_motor_with_bluetooth.Motors.Motor2, kitronik_klip_motor_with_bluetooth.MotorDirection.Forward, 75)
    basic.pause(2000)
    kitronik_klip_motor_with_bluetooth.motorOff(kitronik_klip_motor_with_bluetooth.Motors.Motor1)
    kitronik_klip_motor_with_bluetooth.motorOff(kitronik_klip_motor_with_bluetooth.Motors.Motor2)
    basic.pause(500)
    kitronik_klip_motor_with_bluetooth.motorOn(kitronik_klip_motor_with_bluetooth.Motors.Motor1, kitronik_klip_motor_with_bluetooth.MotorDirection.Reverse, 50)
    kitronik_klip_motor_with_bluetooth.motorOn(kitronik_klip_motor_with_bluetooth.Motors.Motor2, kitronik_klip_motor_with_bluetooth.MotorDirection.Reverse, 50)
    basic.pause(2000)
    kitronik_klip_motor_with_bluetooth.motorOff(kitronik_klip_motor_with_bluetooth.Motors.Motor1)
    kitronik_klip_motor_with_bluetooth.motorOff(kitronik_klip_motor_with_bluetooth.Motors.Motor2)
})